### ISSUE TITLE
About the crop_size of BYOL?

### ISSUE THREAD

**Issue by williamzhao95** [untitled-ai/self_supervised#8]
I found that the default BYOL configuration in this repository has an image size of 96, which is different from the setting in the original paper, and I'd like to ask if this has any effect on the results

**Comment by williamzhao95** [comment]
I found that the default BYOL configuration in this repository has an image size of 96, which is different from the setting in the original paper, and I'd like to ask if this has any effect on the results

**Comment by abefetterman** [comment]
Hi @williamzhao95 ,

Thanks for your note! The default configuration runs on STL10 which has an image size of 96, which is why this crop size is used. The original paper only used ImageNet and has a larger crop size which can be set with that flag. The smaller size is significantly faster for training and requires fewer GPUs, making it more appropriate for testing.

Good luck!
Abe
